app/__init__.py
from flask import Flask

import mysql.connector 


# db = list()
db = mysql.connector.connect( # LLAMAMOS AL FUNCION CONNECT PARA CONECTARNOS
    host ='informatica.iesquevedo.es',
    port = 3333,
    user ='root', #USUARIO QUE USAMOS NOSOTROS
    password ='1asir', #CONTRASEÑA CON LA QUE NOS CONECTAMOS
    database='raul'
) 



def create_app():
    app = Flask(__name__)
    app.debug = True
    

    

    from .routes import routes

    app.register_blueprint(routes.rutas_usuarios)

    return app

app/routes/routes.py
from flask import Blueprint, render_template, request,redirect

from app import db
from app.data.alumno_dao import AlumnoDao
from app.data.notas_dao import NotasDao
from app.data.modelo.alumno import Alumno
from app.data.modelo.notas import Notas

rutas_usuarios = Blueprint("routes", __name__)

@rutas_usuarios.route('/')
def alumnos():
    alumnoDao = AlumnoDao()
    alumnos = alumnoDao.select_all(db)
    return render_template('index.html', alumnos=alumnos)

@rutas_usuarios.route('/insertar', methods=['POST'])
def insert_user():
    nombre = request.form['nombre']
    apellido = request.form['apellido']
    alumnoDao = AlumnoDao()
    alumnoDao.insert_user(db,nombre,apellido)
    return redirect('/')

@rutas_usuarios.route('/delete',methods=['POST'])
def del_user():
    id = request.form['id']
    alumnoDao = AlumnoDao()
    alumnoDao.del_user(db,id)
    return redirect('/')

@rutas_usuarios.route('/edit',methods=['POST'])
def edit_user():
    id = request.form['id']
    nombre = request.form['nombre']
    apellido = request.form['apellido']
    alumnoDao = AlumnoDao()
    alumnoDao.edit_user(db,id,nombre,apellido)
    return redirect('/')

@rutas_usuarios.route('/notas')
def notas():
    notasDao = NotasDao()
    notasDao = notasDao.select_all(db)
    return render_template('notas.html', notas= notasDao)
   
@rutas_usuarios.route('/insertar_nota', methods=['POST'])
def insert_nota():
    id_alumno = request.form['id_alumno']
    seguridad = request.form['seguridad']
    implantacion = request.form['implantacion']
    redes = request.form['redes']
    ingles = request.form['ingles']
    notasDao = NotasDao()
    notasDao.insert_nota(db,id_alumno,seguridad,implantacion,redes,ingles)
    return redirect('/notas')

@rutas_usuarios.route('/delete_nota',methods=['POST'])
def del_nota():
    id_alumno = request.form['id_alumno']
    notasDao = NotasDao()
    notasDao.del_nota(db,id_alumno)
    return redirect('/notas')

@rutas_usuarios.route('/edit_nota',methods=['POST'])
def edit_nota():
    id_alumno = request.form['id_alumno']
    seguridad = request.form['seguridad']
    implantacion = request.form['implantacion']
    redes = request.form['redes']
    ingles = request.form['ingles']
    notasDao = NotasDao()
    notasDao.edit_nota(db,id_alumno,seguridad,implantacion,redes,ingles)
    return redirect('/notas')

app/templates/Notas.html
<head>
    {% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</head>
{% block title %} <h1 style="text-align: center;">Notas de los alumnos</h1>{% endblock %}
{% block content %}
<br>
<h3 style="text-align: center;">Inserción de notas</h3>
<form action="{{url_for('routes.insert_nota')}}" method="POST" style="margin-left: 5%;">
    <div class="row mb-2">
        <div class="col">
            <label>ID</label>
            <input type="text" class="form-control mb-2" name="id_alumno">
        </div>
        <div class="col">
            <label>Seguridad</label>
            <input type="text" class="form-control mb-2" name="seguridad">
        </div>
        <div class="col">
            <label>Implantacion</label>
            <input type="text" class="form-control mb-2" name="implantacion">
        </div>
        <div class="col">
            <label>Redes</label>
            <input type="text" class="form-control mb-2" name="redes">
        </div>
        <div class="col">
            <label>Ingles</label>
            <input type="text" class="form-control mb-2" name="ingles">
        </div>
        <div class="col">
            <button class="btn btn-primary mb-2 mt-3" type="submit">Insertar</button>
        </div>
    </div>
</form>
<h3 style="text-align: center;">Edición de notas</h3>
<form action="{{url_for('routes.edit_nota')}}" method="POST" style="margin-left: 5%;">
    <div class="row mb-2">
        <div class="col">
            <label>ID</label>
            <input type="text" class="form-control mb-2" name="id_alumno">
        </div>
        <div class="col">
            <label>Seguridad</label>
            <input type="text" class="form-control mb-2" name="seguridad">
        </div>
        <div class="col">
            <label>Implantacion</label>
            <input type="text" class="form-control mb-2" name="implantacion">
        </div>
        <div class="col">
            <label>Redes</label>
            <input type="text" class="form-control mb-2" name="redes">
        </div>
        <div class="col">
            <label>Ingles</label>
            <input type="text" class="form-control mb-2" name="ingles">
        </div>
        <div class="col">
            <button class="btn btn-primary mb-2 mt-3" type="submit">Editar</button>
        </div>
    </div>
</form>

<h3 style="text-align: center;">Visualización de notas</h3>
<div style="text-align: center; margin-left: 10%; margin-right: 10%;">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Seguridad</th>
                <th>Implantacion</th>
                <th>Redes</th>
                <th>Ingles</th>
            </tr>
        </thead>
        {% for notas in notas %}
        <tr>
            <td>{{notas.id_alumno}}</td>
            <td>{{notas.nombre}}</td>
            <td>{{notas.seguridad}}</td>
            <td>{{notas.implantacion}}</td>
            <td>{{notas.redes}}</td>
            <td>{{notas.ingles}}</td>
        </tr>
        {% endfor %}
    </table>
</div>
<h3 style="text-align: right; margin-right: 12.5%;">Eliminar notas</h3>

<form action="{{url_for('routes.del_nota')}}" method="POST" style="text-align: right; margin-right: 10%;">
    <div class="row mb-2">
        <div class="col">
            <label>ID</label>
            <input type="number" name="id_alumno">
            <button class="btn btn-primary mb-2 mt-3" type="submit">Borrar</button>
        </div>
    </div>
</form>



<a href="{{ url_for('routes.alumnos') }}">Información de los alumnos</a>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
    <title>{% block title %}{% endblock %}</title>
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</head>
<body>
    <div id="content">{% block content %}{% endblock %}</div>
   
</body>
</html>

app/templates/index.html
{% extends "base.html" %}
{% block title %}Index{% endblock %}


{% block content %}
    
   <h1 style="text-align: center;">Tabla de Información de los alumnos a</h1>
   <h1>Prueba actions</h1>
   <br>
   <h3 style="text-align: center;">Inserción de alumnos</h3>
    <form action="{{url_for('routes.insert_user')}}" method="POST" style="margin-left: 19%;">
        <div class="row mb-2">
            <div class="col">
                <label>Nombre</label>
                <input type="text" class="form-control mb-2" name="nombre">
            </div>
            <div class="col">
                <label>Apellido</label>
                <input type="text" class="form-control mb-2" name="apellido">
            </div>
            <div class="col">
                <button class="btn btn-primary mb-2 mt-3" type="submit">Insertar</button>
            </div>
        </div>

    </form>
    <h3 style="text-align: center;">Edición de alumnos</h3>
    <form action="{{url_for('routes.edit_user')}}" method="POST" style="margin-left: 12%;">
        <div class="row mb-2">
            <div class="col">
                <label>ID</label>
                <input type="text" class="form-control mb-2" name="id">
            </div>
            <div class="col">
                <label>Nombre</label>
                <input type="text" class="form-control mb-2" name="nombre">
            </div>
            <div class="col">
                <label>Apellido</label>
                <input type="text" class="form-control mb-2" name="apellido">
            </div>
            <div class="col">
                <button class="btn btn-primary mb-2 mt-3" type="submit">Editar</button>
            </div>
        </div>

    </form>


    <h3 style="text-align: center;">Visualización de alumnos</h3>
    <div style="text-align: center; margin-left: 10%; margin-right: 10%;">
        <table class="table table-bordered">
            
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Apellido</th>
                </tr>
           
            {% for alumno in alumnos %}
            <tr>
                <td>{{alumno.id}}</td>
                <td>{{alumno.nombre}}</td>
                <td>{{alumno.apellido}}</td>
                
            </tr>
            {% endfor %}
        </table>
    </div>
    <h3 style="text-align: right; margin-right: 12.5%;">Eliminar alumno</h3>
    <form action="{{url_for('routes.del_user')}}" method="POST" style="text-align: right; margin-right: 10%;">
        <div class="row mb-2">
            <div class="col">
                <label>ID</label>
                <input type="number" name="id">
                <button class="btn btn-primary" type="submit">Borrar</button>
            </div>
        </div>
    </form>

    <a href="{{ url_for('routes.notas') }}">Notas de los alumnos</a>
{% endblock %}